# Generated by Django 6.0.5 on 2026-05-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'IT Manager'), ('USER', 'End User')], default='USER', max_length=20),
        ),
    ]
