# Generated by Django 6.0.5 on 2026-05-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'IT Manager'), ('TECHNICIAN', 'IT Technician'), ('ANALYST', 'Security Analyst'), ('USER', 'End User')], default='USER', max_length=20),
        ),
    ]
