# Generated by Django 6.0.5 on 2026-06-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(default='Employee', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'System Manager'), ('RESPONDER', 'Incident Responder'), ('USER', 'End User')], default='USER', max_length=20),
        ),
    ]
