# Generated by Django 6.0.5 on 2026-05-30 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ticket_type', models.CharField(choices=[('HELPDESK', 'IT Helpdesk Ticket'), ('INCIDENT', 'Security Incident')], default='HELPDESK', max_length=20)),
                ('nist_stage', models.CharField(choices=[('PREPARATION', 'Preparation'), ('DETECTION', 'Detection & Analysis'), ('CONTAINMENT', 'Containment'), ('RECOVERY', 'Eradication & Recovery'), ('POST_INCIDENT', 'Post-Incident Activity')], default='PREPARATION', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('new_stage', models.CharField(blank=True, choices=[('PREPARATION', 'Preparation'), ('DETECTION', 'Detection & Analysis'), ('CONTAINMENT', 'Containment'), ('RECOVERY', 'Eradication & Recovery'), ('POST_INCIDENT', 'Post-Incident Activity')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tickets.ticket')),
            ],
        ),
    ]
