# Generated by Django 6.0.5 on 2026-05-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='incident_evidence/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='impact',
            field=models.CharField(choices=[('LOW', 'Low (Single User)'), ('MEDIUM', 'Medium (Department)'), ('HIGH', 'High (Site)'), ('CRITICAL', 'Critical (Enterprise)')], default='LOW', max_length=10),
        ),
    ]
