# Generated by Django 6.0.5 on 2026-05-31 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_attachment_ticket_impact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='impact',
        ),
    ]
